- img: /assets/products/p02.jpg
  title: 塔型系列
  desc: 品质是永恒的主题，服务是不变的承诺

- img: /assets/products/p03.jpg
  title: 三角形系列
  desc: 品质是永恒的主题，服务是不变的承诺

- img: /assets/products/p04.jpg
  title: 破碎剪、液压剪、液压钳
  desc: 品质是永恒的主题，服务是不变的承诺

- img: /assets/products/p09.jpg
  title: 配套机型
  desc: 品质是永恒的主题，服务是不变的承诺
